/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteImport } from './routes/_panel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PanelIndexRouteImport } from './routes/_panel.index'
import { Route as PanelSlugRouteImport } from './routes/_panel.$slug'
import { Route as PanelAdminRouteImport } from './routes/_panel.admin'
import { Route as PanelModsRouteImport } from './routes/_panel.mods'
import { Route as PanelStatsRouteImport } from './routes/_panel.stats'
import { Route as PanelSuspiciousRouteImport } from './routes/_panel.suspicious'
import { Route as PanelTopsRouteImport } from './routes/_panel.tops'
import { Route as PanelPlayerSteamidRouteImport } from './routes/_panel.player.$steamid'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const PanelRoute = PanelRouteImport.update({
  id: '/_panel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelIndexRoute = PanelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSlugRoute = PanelSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminRoute = PanelAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PanelRoute,
} as any)
const PanelModsRoute = PanelModsRouteImport.update({
  id: '/mods',
  path: '/mods',
  getParentRoute: () => PanelRoute,
} as any)
const PanelStatsRoute = PanelStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => PanelRoute,
} as any)
const PanelSuspiciousRoute = PanelSuspiciousRouteImport.update({
  id: '/suspicious',
  path: '/suspicious',
  getParentRoute: () => PanelRoute,
} as any)
const PanelTopsRoute = PanelTopsRouteImport.update({
  id: '/tops',
  path: '/tops',
  getParentRoute: () => PanelRoute,
} as any)
const PanelPlayerSteamidRoute = PanelPlayerSteamidRouteImport.update({
  id: '/player/$steamid',
  path: '/player/$steamid',
  getParentRoute: () => PanelRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PanelIndexRoute
  '/login': typeof LoginRoute
  '/$slug': typeof PanelSlugRoute
  '/admin': typeof PanelAdminRoute
  '/mods': typeof PanelModsRoute
  '/stats': typeof PanelStatsRoute
  '/suspicious': typeof PanelSuspiciousRoute
  '/tops': typeof PanelTopsRoute
  '/player/$steamid': typeof PanelPlayerSteamidRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$slug': typeof PanelSlugRoute
  '/admin': typeof PanelAdminRoute
  '/mods': typeof PanelModsRoute
  '/stats': typeof PanelStatsRoute
  '/suspicious': typeof PanelSuspiciousRoute
  '/tops': typeof PanelTopsRoute
  '/': typeof PanelIndexRoute
  '/player/$steamid': typeof PanelPlayerSteamidRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_panel': typeof PanelRouteWithChildren
  '/login': typeof LoginRoute
  '/_panel/$slug': typeof PanelSlugRoute
  '/_panel/admin': typeof PanelAdminRoute
  '/_panel/mods': typeof PanelModsRoute
  '/_panel/stats': typeof PanelStatsRoute
  '/_panel/suspicious': typeof PanelSuspiciousRoute
  '/_panel/tops': typeof PanelTopsRoute
  '/_panel/': typeof PanelIndexRoute
  '/_panel/player/$steamid': typeof PanelPlayerSteamidRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$slug'
    | '/admin'
    | '/mods'
    | '/stats'
    | '/suspicious'
    | '/tops'
    | '/player/$steamid'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$slug'
    | '/admin'
    | '/mods'
    | '/stats'
    | '/suspicious'
    | '/tops'
    | '/'
    | '/player/$steamid'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_panel'
    | '/login'
    | '/_panel/$slug'
    | '/_panel/admin'
    | '/_panel/mods'
    | '/_panel/stats'
    | '/_panel/suspicious'
    | '/_panel/tops'
    | '/_panel/'
    | '/_panel/player/$steamid'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PanelRoute: typeof PanelRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_panel': {
      id: '/_panel'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_panel/': {
      id: '/_panel/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PanelIndexRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/$slug': {
      id: '/_panel/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof PanelSlugRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/admin': {
      id: '/_panel/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PanelAdminRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/mods': {
      id: '/_panel/mods'
      path: '/mods'
      fullPath: '/mods'
      preLoaderRoute: typeof PanelModsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/stats': {
      id: '/_panel/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof PanelStatsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/suspicious': {
      id: '/_panel/suspicious'
      path: '/suspicious'
      fullPath: '/suspicious'
      preLoaderRoute: typeof PanelSuspiciousRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/tops': {
      id: '/_panel/tops'
      path: '/tops'
      fullPath: '/tops'
      preLoaderRoute: typeof PanelTopsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/_panel/player/$steamid': {
      id: '/_panel/player/$steamid'
      path: '/player/$steamid'
      fullPath: '/player/$steamid'
      preLoaderRoute: typeof PanelPlayerSteamidRouteImport
      parentRoute: typeof PanelRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PanelRouteChildren {
  PanelSlugRoute: typeof PanelSlugRoute
  PanelAdminRoute: typeof PanelAdminRoute
  PanelModsRoute: typeof PanelModsRoute
  PanelStatsRoute: typeof PanelStatsRoute
  PanelSuspiciousRoute: typeof PanelSuspiciousRoute
  PanelTopsRoute: typeof PanelTopsRoute
  PanelIndexRoute: typeof PanelIndexRoute
  PanelPlayerSteamidRoute: typeof PanelPlayerSteamidRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelSlugRoute: PanelSlugRoute,
  PanelAdminRoute: PanelAdminRoute,
  PanelModsRoute: PanelModsRoute,
  PanelStatsRoute: PanelStatsRoute,
  PanelSuspiciousRoute: PanelSuspiciousRoute,
  PanelTopsRoute: PanelTopsRoute,
  PanelIndexRoute: PanelIndexRoute,
  PanelPlayerSteamidRoute: PanelPlayerSteamidRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PanelRoute: PanelRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
